[package]
name = "rust-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
aes = "0.8.4"
anyhow = "1.0.99"
base64 = "0.22.1"
cbc = "0.1.2"
sha2 = "0.10.9"
thiserror = "2.0.16"
wasm-bindgen = "0.2.101"
